import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DOMParser,parseHTML} from 'linkedom';
const dom=parseHTML('<html><head></head><body></body></html>');globalThis.document=dom.document;globalThis.DOMParser=DOMParser;
const {parseDeck}=await import('../src/deck.js');
const {elementOperations,slideOperations,documentMeta,setDocumentMeta}=await import('../src/editor-model.js');
const {shapeHTML,layoutHTML}=await import('../src/authoring.js');
const raw='<html><head><title>Test</title><style>h1{color:red}</style></head><body>\n<section id="a"><h1>A</h1><p>One</p></section>\n<!-- keep this comment -->\n<section id="b"><h1>B</h1></section>\n<section id="c"><h1>C</h1></section>\n<section id="d"><h1>D</h1></section></body></html>';
test('manual and agent operations retain text, identify targets and preserve neighboring objects',()=>{const out=elementOperations(parseDeck(raw).slides[0].html,[{type:'style',target:[0],style:{color:'#336699','font-size':'64px'}}]);assert.match(out,/data-dek-id=/);assert.match(out,/color:#336699/);assert.match(out,/<p>One<\/p>/);assert.match(out,/>A<\/h1>/);});
test('batch hide is persistent and respects legacy skip attributes',()=>{const m=parseDeck(slideOperations(parseDeck(raw),[0,2],'hide'));assert.deepEqual(m.slides.map(s=>!!s.skip),[true,false,true,false]);assert.match(m.raw,/keep this comment/);const shown=parseDeck(slideOperations(m,[0,2],'show'));assert.ok(shown.slides.every(s=>!s.skip));});
test('batch move preserves relative order and non-slide source',()=>{const m=parseDeck(slideOperations(parseDeck(raw),[0,2],'move',{to:2}));assert.deepEqual(m.slides.map(s=>s.id),['b','d','a','c']);assert.match(m.raw,/<!-- keep this comment -->/);assert.equal(m.headInner,parseDeck(raw).headInner);});
test('duplicate slides has unique slide and editor IDs',()=>{const m=parseDeck(slideOperations(parseDeck(raw),[0,2],'duplicate'));assert.equal(m.slides.length,6);assert.equal(new Set(m.slides.map(s=>s.id)).size,6);assert.deepEqual(m.slides.map(s=>s.title),['A','B','C','A','C','D']);});
test('section metadata adds no slide wrappers',()=>{let m=parseDeck(setDocumentMeta(parseDeck(raw),{version:1,sections:[{id:'intro',name:'Introduction'}]}));m=parseDeck(slideOperations(m,[0,1],'section',{id:'intro'}));assert.equal(m.slides.length,4);assert.equal(m.slides[0].section,'intro');assert.equal(documentMeta(m).sections[0].name,'Introduction');});
test('locking prevents modifications and unlock is reversible',()=>{const locked=elementOperations('<section><p>Text</p></section>',[{type:'lock',target:[0],locked:true}]);assert.throws(()=>elementOperations(locked,[{type:'delete',target:[0]}]),/Unlock/);const out=elementOperations(locked,[{type:'lock',target:[0],locked:false},{type:'style',target:[0],style:{color:'blue'}}]);assert.match(out,/color:blue/);});
test('grouping then ungrouping retains content',()=>{const html='<section><p>A</p><p>B</p></section>';const positions=[{x:10,y:20,w:100,h:40},{x:200,y:20,w:100,h:40}];const group=elementOperations(html,[{type:'group',targets:[[0],[1]],box:{x:10,y:20,w:290,h:40},positions}]);assert.match(group,/dek-group/);const out=elementOperations(group,[{type:'ungroup',target:[0],positions}]);assert.doesNotMatch(out,/dek-group/);assert.match(out,/>A<\/p>/);assert.match(out,/>B<\/p>/);});
test('deleting every slide leaves a valid empty HTML deck',()=>{const m=parseDeck(slideOperations(parseDeck(raw),[0,1,2,3],'delete'));assert.equal(m.slides.length,0);assert.match(m.raw,/<title>Test<\/title>/);});
test('shape and layout insertion are complete HTML fragments',()=>{for(const shape of ['rectangle','rounded','ellipse','line','arrow','triangle'])assert.match(shapeHTML({shape}),new RegExp(`data-shape="${shape}"`));for(const layout of ['blank','title','content','split','quote'])assert.equal(parseDeck(layoutHTML(layout)).slides.length,1);assert.throws(()=>shapeHTML({shape:'unknown'}));});

const {copySlidesInto,reorderSections,ensureObjectIds,freshSlide}=await import('../src/editor-model.js');
test('shape insertion uses the shared slide mutation layer',()=>{const out=elementOperations('<section><h1>Keep</h1></section>',[{type:'insert',target:':scope',html:shapeHTML({shape:'ellipse'})}]);assert.match(out,/data-shape="ellipse"/);assert.match(out,/>Keep</);});
test('stable object identifiers survive repeated edits without changing animation identifiers',()=>{const source='<html><head><style>h1{color:red}</style></head><body><!-- keep --><section id="a"><h1 data-id="hero">Hello <em>world</em></h1><svg><path d="M0 0L1 1"/></svg></section></body></html>';const once=ensureObjectIds(source);assert.equal(ensureObjectIds(once),once);assert.match(once,/data-id="hero"/);assert.match(once,/<!-- keep -->/);const ids=[...once.matchAll(/data-dek-id="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,4);});
test('copying slides resolves component collisions and preserves destination design',()=>{const destination='<html><head><style>h1{color:blue}</style><template data-dek-component="badge"><b>Destination</b></template></head><body><section id="one"><h1>Existing</h1></section></body></html>';const source='<section id="one" data-dek-section="old"><div data-dek-use="badge"></div></section>';const out=parseDeck(copySlidesInto(parseDeck(destination),{html:source,head:'<template data-dek-component="badge"><i>Source</i></template>'}));assert.equal(out.slides.length,2);assert.notEqual(out.slides[1].id,'one');assert.match(out.headInner,/h1\{color:blue\}/);assert.match(out.slides[1].html,/data-dek-use="badge-/);assert.doesNotMatch(out.slides[1].html,/data-dek-section/);assert.match(out.headInner,/<i>Source<\/i>/);});
test('reordering a named section reorders its slides, preserving their order',()=>{let m=parseDeck(raw);m=parseDeck(slideOperations(m,[0,1],'section',{id:'first'}));m=parseDeck(slideOperations(m,[2,3],'section',{id:'last'}));m=parseDeck(reorderSections(m,[{id:'last',name:'Last'},{id:'first',name:'First'}]));assert.deepEqual(m.slides.map(s=>s.id),['c','d','a','b']);assert.match(m.raw,/keep this comment/);});
test('duplicated embedded SVG retains local reference integrity',()=>{const out=freshSlide('<section id="old"><svg><defs><linearGradient id="paint"></linearGradient></defs><rect fill="url(#paint)"/></svg><a href="#old">Top</a></section>',[]);const doc=new DOMParser().parseFromString(out,'text/html');const id=doc.querySelector('linearGradient').id;assert.notEqual(id,'paint');assert.equal(doc.querySelector('rect').getAttribute('fill'),`url(#${id})`);assert.equal(doc.querySelector('a').getAttribute('href'),'#'+doc.querySelector('section').id);});
test('legacy update and nested targets honor locked objects',()=>{const html='<section><div data-dek-locked><p>Keep</p></div></section>';assert.throws(()=>elementOperations(html,[{type:'update',target:[0,0],text:'Lost'}]),/Unlock/);assert.throws(()=>elementOperations(html,[{type:'delete',target:[0,0]}]),/Unlock/);});

test('speaker notes retain line breaks and ampersands',()=>{const m=parseDeck('<section><aside class="notes"><span>Notes &amp; reminders<br>Second line</span></aside></section>');assert.equal(m.slides[0].notes,'Notes & reminders\nSecond line');});
test('duplicating objects rewrites exact IDs without corrupting overlapping IDs or colors',()=>{const out=freshSlide('<section id="a"><style>#paint-long{fill:#abc}</style><svg><defs><linearGradient id="paint"></linearGradient><linearGradient id="paint-long"></linearGradient></defs><rect fill="url(#paint-long)" stroke="#abc"/></svg></section>');const doc=new DOMParser().parseFromString(out,'text/html');const gradients=doc.querySelectorAll('linearGradient');assert.equal(doc.querySelector('rect').getAttribute('fill'),`url(#${gradients[1].id})`);assert.equal(doc.querySelector('rect').getAttribute('stroke'),'#abc');assert.match(doc.querySelector('style').textContent,new RegExp(gradients[1].id));});
test('copying components carries local script and scoped style dependencies without global source theme',()=>{const out=copySlidesInto(parseDeck(raw),{html:'<section><widget-card></widget-card></section>',head:'<script src="assets/widget.js"></script><style data-dek-dependency="widget">widget-card{display:block}</style><style>body{background:red}</style>'});assert.match(out,/src="assets\/widget.js"/);assert.match(out,/data-dek-dependency="widget"/);assert.doesNotMatch(out,/background:red/);});
const {convertDeckStage}=await import('../src/import.js');
test('imported HTML retains identifiers, animation conventions, complex visuals and notes',()=>{const foreign='<html><head><style>.chart{color:blue}</style></head><body><deck-stage width="1440" height="900"><section id="keep" data-speaker-notes="First &amp; second"><h1 data-id="hero">Imported</h1><svg class="chart"><path d="M0 0L1 1"/></svg><p class="fragment">Reveal</p></section></deck-stage></body></html>';const result=convertDeckStage(foreign,{title:'Imported deck'});assert.equal(result.count,1);assert.deepEqual(result.size,{w:1440,h:900});const deck=parseDeck(result.html);assert.equal(deck.slides[0].id,'keep');assert.match(deck.slides[0].html,/data-id="hero"/);assert.match(deck.slides[0].html,/<svg class="chart">/);assert.match(deck.slides[0].html,/class="fragment"/);assert.equal(deck.slides[0].notes,'First & second');});

const {transferHead}=await import('../src/editor-model.js');
test('cross-deck copy includes components defined in the source body',()=>{const source=parseDeck('<html><head></head><body><template data-dek-component="body-badge"><b>Reusable body component</b></template><section><div data-dek-use="body-badge"></div></section></body></html>');const out=copySlidesInto(parseDeck(raw),{html:source.slides[0].html,head:transferHead(source)});assert.match(out,/<template data-dek-component="body-badge">/);assert.match(out,/Reusable body component/);});
